name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          # probot/example-google-cloud-function credentials provided by @bcoe
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy to GCF
        run: |
          gcloud functions deploy example-google-cloud-function \
            --runtime nodejs12 \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point probotApp \
            --set-env-vars APP_ID="${{secrets.APP_ID}}",PRIVATE_KEY="${{secrets.PRIVATE_KEY}}",WEBHOOK_SECRET="${{secrets.WEBHOOK_SECRET}}"
